services:
  - type: web
    plan: free
    name: Pbxnew
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash setup
    repo: https://github.com/Badhacker98/PBX_2.0
    branch: master
    autoDeploy: False
    envVars:
    - key: BOT_TOKEN
      sync: false
     - key: API_HASH
      sync: false
     - key: API_ID
      sync: false
     - key: DATABASE_URL
      sync: false
     - key: HANDLERS
      sync: false
     - key: LOGGER_ID
      sync: false
     - key: OWNER_ID
      sync: false
     - key: PLUGINS_REPO
      sync: false
     - key: DEPLOY_REPO
      sync: false
